name: cancel-action
description: "Cancelling redundand workglow runs"
author: kuritka
# see: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: grid
  color: red
inputs:
  cancel-when-job-successfully-passed:
    description: "(Optional) A job is automatically cancelled if it has been successfully passed in the past."
    required: false
    default: "false"
  remove-artifact:
    description: "(Optional) If a cancel occurs, it automatically removes the artifact."
    required: false
    default: "false"
  verbose:
    description: "(Optional) verbose output."
    required: false
    default: "false"
  token:
    description: '(Optional) Github token.'
    required: true
    default: ${{ github.token }}

runs:
  using: composite
  steps:
   # TODO: consider to put it into composite action
    - uses: actions/setup-go@v2
      with:
        go-version: "1.17.6"

    - id: prepare-development
      shell: bash
      if: ${{ github.ref == 'refs/heads/master' }}
      run: echo "DEVELOPMENT RUN"

    - id: prepare-release
      shell: bash
      if: ${{ github.ref != 'refs/heads/master' }}
      run: echo "RELEASE RUN"

    - id: main
      shell: bash
      run: |
        cd ${{ github.action_path }}
        go mod tidy
        go run main.go cancel
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
        GITHUB_RUN_ID: ${{ env.GITHUB_RUN_ID }}
        CANCEL_WHEN_JOB_SUCCESSFULLY_PASSED: ${{ inputs.cancel-when-job-successfully-passed }}
        REMOVE_ARTIFACT: ${{ inputs.remove-artifact }}
        VERBOSE: ${{ inputs.verbose }}

