name: Lint, Tests, Inspect
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  go-build:
    name: Inspect packages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
       # see: https://golangci-lint.run/usage/configuration/#config-file
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.42.1

      - name: go test
        run: go test ./...

